/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "DocAiApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "DocAiBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "DocAiResultsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "DocAiTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "IsapreTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "ProcessDocAi": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SaveResults": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UploadHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ValidateIsapre": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}